<?php
$this->layout()->title = $this->translate('Players overview');
$db = Zend_Registry::get('db');
?>
<section class=categories>
    <table>
        <thead>
            <tr>
                <th><?php echo $this->translate('Player');?>
                <th><?php echo $this->translate('Team');?>
                <th><?php echo $this->translate('Position');?>
                <th><?php echo $this->translate('Steam ID');?>
                <th><?php echo $this->translate('Nationality');?>
                <th width="90">Active
                <th width="50">&nbsp;
                <th width="50">&nbsp;
        </thead>
        <tbody>
            <?php 
            $items = $this->items;
            foreach($items as $i => $item):
    	        $q = $db->prepare('SELECT club FROM clubs WHERE id = :club_id');
    	    	$q->bindValue(':club_id', $item['club_id']);
				$q->execute();

				$club = $q->fetch(PDO::FETCH_ASSOC);
           	?>
            <tr>
                <td><?php echo $item['name']; ?></td>
                <td><?php echo $club['club']; ?></td>
                <td><?php echo $item['pos']; ?></td>
                <td><?php echo $item['steam_id']; ?></td>
                <td><img src="../assets/img/flags/small/<?php echo $item['nation']; ?>" /></td>
                <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id'])) ?>"><?php echo $this->translate('Update');?></a></td>
                <td class=delete><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id'])) ?>"><?php echo $this->translate('Delete');?></a></td>
            </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</section>