<?php
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$form   = $this->form;
$forms  = $form->getSubForms();

$submit = '<input type=submit class=button value="' . $this->translate('Save')  . '" />';
?>
       
<form class="standard" method=POST>
    
<div class="content-box">
    <div class="content-box-header">
         <ul class="content-box-tabs">
            <li><a href="#tabgeneral" class="current">General</a></li>
            <?php
            $j = 0;
            foreach($forms as $i => $subform):
            ?>
            <?php
            if($j == 0)
            {
                echo '<li><a href="#tab'. $subform->getName() .'">'. $subform->getName() .'</a></li>';
            }
            else
            {
                echo '<li><a href="#tab'. $subform->getName() .'">'. $subform->getName() .'</a></li>';
            }
            ?>
            <?php
            $j++;
            endforeach;
            ?>
        </ul> 
        <div class="clear"></div>
    </div>
    <div class="content-box-content">
        
        <!-- General info -->
        <div class="tab-content default-tab" id="tabgeneral" >
            <p>
                <label class=required><?php echo $this->translate('Category');?></label>
                <?php echo $form->getElement('parent_id') ?>
            </p>
            <p>
                <?php echo $submit;?>
            </p>  

            <div class="clear"></div>
            
        </div>

        <!-- Language info -->
        <?php
        foreach($forms as $i => $subform):
        ?>        
        <div class="tab-content" id="tab<?php echo $i;?>"> 
            <p>
                <label class=required><?php echo $this->translate('Name');?></label>
                <?php echo $subform->getElement('name') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Content');?></label>
                <?php echo $subform->getElement('content') ?>
            </p>
            <p>
                <?php echo $submit;?>
            </p>   
        </div>
        <?php
        endforeach;
        ?>
        
    </div>
</div>

</form>  

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){

    // display hidden images
    $('.image_preview').each(function(){
        if($(this).attr('src') != '../')
            $(this).show();
    });

    var active = '';    
    function SetFileField(fileUrl) {
        $('.image' + active).val(fileUrl);
        $('.preview' + active).attr('src','../' + fileUrl).show();
    }
    
    var finder = new CKFinder();
    finder.selectActionFunction = SetFileField;
    $(".image_browser").bind("click", function(){ 
        active = $(this).attr('rel');
        finder.popup();
    });
}); 
<?php $this->headScript()->captureEnd(); 
?>