 <?php $db = Zend_Registry::get('db'); ?>
 
 <div id="myCarousel" class="carousel slide">

          <div class="carousel-inner">
	      	<?php
	  			foreach( $this->slides as $slide):
					echo '<div class="item">
	        				<img src="' . $slide['image'] . '" />
	            				<div class="carousel-caption">
				                    <h4>' . $slide['title'] . '</h4>
				                    <p>' . $slide['text'] . '</p>
				                </div>
	        			 </div>';
				  endforeach;
	      	?>
	      </div>

        <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>

</div>

<div id="left">

<?php
	foreach( $this->news as $item):
		echo '<article>
	            <div class="post clearfix">
	              <div class="post-left">
	                  <img src="' . $item['image'] . '">
	              </div>
	              <div class="post-right">
	                <h2>' . $item['title'] . '</h2>
	                <p class="posted-by">' . date("F d Y H:i", strtotime( $item['date_created'] ) ) . ', by ' . $item['author'] . '</p>
	                <p class="description">' . strip_tags(substr($item['text'], 0, 300)) . '...' . '</p>
	              	<a class="read-more" href="news/' . $item['url'] . '">Read More</a>
	              </div>
	            </div>
			</article>';
	endforeach; 
?>

<a class="more-news" href="<?= $this->baseurl; ?>news">More News</a>

</div>

<div id="right">

          <ul style="font-size: 12px;" class="nav nav-tabs statistics">
		  
            <li class="active"><a href="#goals" data-toggle="tab">Goals</a></li>
            <li><a href="#assists" data-toggle="tab">Assists</a></li>
            <li><a href="#passes" data-toggle="tab">Passes</a></li>
			<li><a href="#interceptions" data-toggle="tab">Interc.</a></li>
			<li><a href="#saves" data-toggle="tab">Saves</a></li>
          </ul>

          <div class="tab-content tabs-content">

            <div class="tab-pane active" id="goals">

              <table class="bordered-table table">

                <thead>

                    <tr>
                      <th>Player</th>
					  <th>Amount</th>
					  
                    </tr>

                </thead>

                <tbody>
				
				<?php 
					$players = $db->fetchAll('SELECT * FROM players ORDER BY goals DESC LIMIT 10');
					foreach($players as $player):
				?>
                    <tr>
                      <td><?php echo $player['name'] ?></td>
                      <td><?php echo $player['goals'] ?></td>
                    </tr>
					
				<?php endforeach; ?>

                </tbody>

              </table>

            </div>
			
		    <div class="tab-pane" id="assists">

              <table class="bordered-table table">

                <thead>

                    <tr>
                      <th>Player</th>
					  <th>Amount</th>
					  
                    </tr>

                </thead>

                <tbody>
				
				<?php 
					$players = $db->fetchAll('SELECT * FROM players ORDER BY assists DESC LIMIT 10');
					foreach($players as $player):
				?>
                    <tr>
                      <td><?php echo $player['name'] ?></td>
                      <td><?php echo $player['assists'] ?></td>
                    </tr>
					
				<?php endforeach; ?>

                </tbody>

              </table>

            </div>
		    <div class="tab-pane" id="passes">

              <table class="bordered-table table">

                <thead>

                    <tr>
                      <th>Player</th>
					  <th>Amount</th>
					  
                    </tr>

                </thead>

                <tbody>
				
				<?php 
					$players = $db->fetchAll('SELECT * FROM players ORDER BY passes DESC LIMIT 10');
					foreach($players as $player):
				?>
                    <tr>
                      <td><?php echo $player['name'] ?></td>
                      <td><?php echo $player['passes'] ?></td>
                    </tr>
					
				<?php endforeach; ?>

                </tbody>

              </table>

            </div>
		    <div class="tab-pane" id="interceptions">

              <table class="bordered-table table">

                <thead>

                    <tr>
                      <th>Player</th>
					  <th>Amount</th>
					  
                    </tr>

                </thead>

                <tbody>
                  
				<?php 
					$players = $db->fetchAll('SELECT * FROM players ORDER BY interceptions DESC LIMIT 10');
					foreach($players as $player):
				?>
                    <tr>
                      <td><?php echo $player['name'] ?></td>
                      <td><?php echo $player['interceptions'] ?></td>
                    </tr>
					
				<?php endforeach; ?>

                </tbody>

              </table>

            </div>
			
			<div class="tab-pane" id="saves">

              <table class="bordered-table table">

                <thead>

                    <tr>
                      <th>Player</th>
					  <th>Amount</th>
					  
                    </tr>

                </thead>

                <tbody>
				
				<?php 
					$players = $db->fetchAll('SELECT * FROM players ORDER BY saves DESC LIMIT 10');
					foreach($players as $player):
				?>
                    <tr>
                      <td><?php echo $player['name'] ?></td>
                      <td><?php echo $player['saves'] ?></td>
                    </tr>
					
				<?php endforeach; ?>

                </tbody>

              </table>

            </div>			
			
		

    </div>

</div>

<script type="text/javascript">

$(document).ready(function() {
	$(".left").click();
})

</script>
