<div class="rules">
				
					<div class="rules-index">
			
						<div class="irc1">
						
						<h2>1. Installtion</h2>
						
						<p>1.1 For players that has no clue how to use IRC. We recommend you to use HexChat.</p>
						
						<p><a href="http://dl.hexchat.org/hexchat/HexChat%202.9.5%20x86.exe">Click here to download the 32 bit version of HexChat</a></p>
						<p><a href="http://dl.hexchat.org/hexchat/HexChat%202.9.5%20x64.exe">Click here to download the 64 bit version of HexChat</a></p>
						
						
						
						<p>1.2 Follow the following pictures:</p>
						
						<img src="assets/img/hex/inst1.png">
						<img src="assets/img/hex/inst2.png">
						<img src="assets/img/hex/inst3.png">
						<p>The directory where you install HexChat</p>
						<img src="assets/img/hex/inst4.png">
						<p>You can include the HexChat-Text and Theme Manager if you want.</p>
						<img src="assets/img/hex/inst5.png">
						<p>This is also your own choice as well.</p>
						<img src="assets/img/hex/inst6.png">
						<img src="assets/img/hex/inst7.png">
							
						
						<h2>2. Settings</h2>
						
						<p>2.1 So now you have installed HexChat. We still need to put the right settings to get on the right IOS channels.</p>
						
						<div class="irc2">
						
							<img src="assets/img/hex/sett1.png">
							
							<p>Fill in your name.</p>
							
							<img src="assets/img/hex/sett2.png">
							
							<p>Click on QuakeNet and 'Skip network list on startup'.</p>
							
							<img src="assets/img/hex/sett3.png">
							
							<p>Click on 'Auto connect to this network at startup'. After that you click on the right side of 'Favorite channels'.</p>
							
							<div class="irc3">
							
								<img src="assets/img/hex/sett4.png">
								
								<p>Click on 'Add'.</p>
								
								<img src="assets/img/hex/sett5.png">
								
								<p>The 3 main IOS channels are: #ioss.mix, #ios.dev and #ios.league.</p>
								
							</div>
							
							<img src="assets/img/hex/sett6.png">
							
							<p>Close.</p>
							
							<img src="assets/img/hex/sett7.png">
							
							<p>Connect!</p>
							
							<div class="irc4">
							
								<img src="assets/img/hex/sett8.png">
								
								<p>Pending.</p>
								
								<img src="assets/img/hex/sett9.png">
								
								<p>Take off 'Always show this dialog after connecting.' So it will not appear again.</p>
								
								<img src="assets/img/hex/sett10.png">	
								
								<p>You can use HexChat with the correct IOS channels now!</p>
														
								<h2>3. Run automaticly </h2>
								
								<p>3.1 We got everything set and done. But you might want to start HexChat everytime when your computer starts.</p>
								
								
								<img src="assets/img/hex/win1.png">
								
								<p>Go to Start &gt; All Programs. Find the folder 'Startup' and Right Click &gt; Open.</p>
								
								<div class="irc5">
								
									<img src="assets/img/hex/win2.png">
									
									<p>Find 'hexchat.exe' in Program Files C:/Program Files (x86)/HexChat/hexchat.exe. Copy and drag it to the Startup folder.</p>
								
								</div>
								
								<img src="assets/img/hex/win3.png">
								
								<p>To be sure if HexChat will start automaticly. Go Start &gt; search for 'System Configuration' and click on it.</p>
								
								<img src="assets/img/hex/win4.png">
								
								<p>Go to the Startup tab. If you see HexChat like on the screenshot, it means that it will startup automaticly!</p>
								
							</div>
							
						</div>
						
						</div>
					
					</div>
					
				</div>