	<div class="rules">
	
		<div class="rules-index">
		
		<h2>Match admin</h2>
		
		<p>Match admins has a lot to do. First of all you have to  <a href="http://www.ios-league.com/rules" target="_blank">read the rules!</a></p>
		
		<p>The rcon password of IOS League #1 you can get from Iran.</p>
		
		<p>1. You have to watch the game! You can not just alt tab and do nothing.</p>
		
		<p>2. Do not get influenced by other players who are asking for a default win or to end a timeout. You just do what you are going to do. You are the 'boss' of that game so you decide!</p>
		
		<p>3. Team names should be written correctfully! <br /> <br />
		
		BB = Ball Breakers <br />
		Bears = Bears <br />
		Gs = Gorillas <br />
		iSS = Inter Soccer Stars <br /> 
		nG = NextGen <br />
		s7 = Super 7 <br /> <br />
		
		You have to use mp_teamnames "TAG1:TEAMNAME1,TAG2:TEAMNAME2" <br /> <br />
		For example if nG faces iSS then it should be mp_teamnames "nG:NextGen,iSS:Inter Soccer Stars" This is extremely important because if there is a typo then the stats won't be counted!</p>
		
		<p>4. Captain of home team decides the stadium that the match will be played on. It's better to ask him at least 1 hour before the game starts. If you can't contact the captain then ask an other player of the same team. If all else fails then just put ioss_7testadium_v3 as default map.</p>
		
		<p>5. You can only chat through 'rcon say [TEXT]'</p>
		
		<p>6. Make sure 'IOS TV' is on spectator. If not restart the map.</p>
		
		<p>7. Kick ALL the players in the server who are not a member of one of the 2 teams. Staff members are allowed to join the server.</p>
		
		<p>8. Control their SteamID's. Use the team page to check. This is very important because if a player plays under a different Steam ID than he signed up. His stats won't be counted.</p>
	
		<p>9. Players should use their real nickname that they are known of. It doesn't need to be that exact like on the website but at least something close to it. For example 'iranian24 (Iran)' is fine but 'Sebastian Giovinco (Zapdos)' is wrong.</p>
		
		<p>10. Make sure the home team plays home and away team plays away!</p>
		
		<p>11. If both captains said 'ready' in chat. Put the warm-up time to 30 seconds (sv_restart 0.5) The game goes live in 30 seconds. </p>
		
		<p>12. When captain calls for 'timeout' on chat. Immediately use 'sv_starttimeout' and do 'sv_endtimeout' when they are ready again. Ask both captains if they are ready!</p>
	
		<p>13. Name 'your' Man of the Match. This won't be the 100% Man of the Match but we take it into consideration. Up the judging panel to decide. </p>
		
		<h2>Server CFG</h2>
		
		<p>The config for the league matches are as followed: <br /> <br />
		
		mp_chat_match_captain_only 1 <br />
		mp_chat_intermissions_captain_only 1 <br />
		sv_autostartmatch 0 <br />
		sv_webserver_matchdata_enabled 1 <br /> <br />
		
		You should change the commands to these values!
		</p>
		
		<h2>Team kits</h2>
		
		<p>You need to use 'mp_teamlist' to activate the kits in the server: <br /> <br />
		
		Ball Breakers = bb/bba <br />
		Bears = bearsh/bearsa <br />
		Gorillas = gorillas/gorillasa <br />
		Inter Soccer Stars = iss/issa <br />
		NextGen = nghome/ngaway <br />
		Super 7 = s7/s7a <br /> <br />
		
		For example if Bears faces Ball Breakers it should be "mp_teamlist bearsh bba" </p>
		</p>
		
		</div>
	
	</div>