
	<form action="poll" method="POST">

		<fieldset class="fieldset">

		<div class="ios-name">
			<label style="color: #FFF; font-family: calibri;" for="name" name="player" required="required">Player: (select your name)</label> <br />
				<select required="required" name="player" id="player" class="span3">
					<option value="">Select your name!</option>
						<option value="Ailton">Ailton</option>
						<option value="Ashley">Ashley</option>
						<option value="Burni">Burni</option>
						<option value="CARLEETOS">CARLEETOS</option>
						<option value="Chalkeh">Chalkeh</option>
						<option value="ChouPo">ChouPo</option>
						<option value="Cuppatea">Cuppatea</option>
						<option value="Daap">Daap</option>
						<option value="DBD">DBD</option>
						<option value="Deluxe">Deluxe</option>
						<option value="Denneh">Denneh</option>
						<option value="Destran">Destran</option>
						<option value="Diakun">Diakun</option>
						<option value="Drogba">Drogba</option>
						<option value="Earneh">Earneh</option>
						<option value="EltonJohn">EltonJohn</option>
						<option value="Filip">Filip</option>
						<option value="Flame">Flame</option>
						<option value="Fluke">Fluke</option>
						<option value="Fonzik">Fonzik</option>
						<option value="Fuzz">Fuzz</option>
						<option value="GaMs">GaMs</option>
						<option value="Ginixx">Ginixx</option>
						<option value="Goldeh">Goldeh</option>
						<option value="Grandie">Grandie</option>
						<option value="Greggles">Greggles</option>
						<option value="Gunner">Gunner</option>
						<option value="h0w">h0w</option>
						<option value="Hexo">Hexo</option>
						<option value="Hiei">Hiei</option>
						<option value="Hpayer">Hpayer</option>
						<option value="Iran">Iran</option>
						<option value="JB3">JB3</option>
						<option value="Kaim">Kaim</option>
						<option value="Kajia">Kajia</option>
						<option value="Kaka22">Kaka22</option>
						<option value="Katsuo">Katsuo</option>
						<option value="Khaledinho">Khaledinho</option>
						<option value="Kirby">Kirby</option>
						<option value="Km">Km</option>
						<option value="Kobe">Kobe</option>
						<option value="LagHack">LagHack</option>
						<option value="Larsson">Larsson</option>
						<option value="Lua">Lua</option>
						<option value="Luisa">Luisa</option>
						<option value="Maaby">Maaby</option>
						<option value="Marsi">Marsi</option>
						<option value="MeanMachine">MeanMachine</option>
						<option value="Modiga">Modiga</option>
						<option value="Monkeyclone">Monkeyclone</option>
						<option value="Moses">Moses</option>
						<option value="Neuromancer">Neuromancer</option>
						<option value="Niang">Niang</option>
						<option value="Night-Fire">Night-Fire</option>
						<option value="Nuri">Nuri</option>
						<option value="Orius">Orius</option>
						<option value="Pauer">Pauer</option>
						<option value="Quincy">Quincy</option>
						<option value="Rage">Rage</option>
						<option value="Rahmstein">Rahmstein</option>
						<option value="Realms">Realms</option>
						<option value="Rhino">Rhino</option>
						<option value="Robi">Robi</option>
						<option value="Romdi">Romdi</option>
						<option value="Roq">Roq</option>
						<option value="RvdV">RvdV</option>
						<option value="Ryaninho">Ryaninho</option>
						<option value="Saddeh">Saddeh</option>
						<option value="Salix">Salix</option>
						<option value="Seaneh">Seaneh</option>
						<option value="Seven|Up">Seven|Up</option>
						<option value="Shagwa">Shagwa</option>
						<option value="Simao">Simao</option>
						<option value="Simu">Simu</option>
						<option value="Skum">Skum</option>
						<option value="Sudders">Sudders</option>
						<option value="Termi">Termi</option>
						<option value="Tet">Tet</option>
						<option value="Thing'e'">Thing'e'</option>
						<option value="TopCat">TopCat</option>
						<option value="Tsubasa">Tsubasa</option>
						<option value="Walsh">Walsh</option>
						<option value="Wilmots">Wilmots</option>
						<option value="XaviT">XaviT</option>
						<option value="Xedem">Xedem</option>
						<option value="Yvus">Yvus</option>
						<option value="Zapdos">Zapdos</option>
						<option value="Zlatan">Zlatan</option>								
				</select>
			</div>

			<div class="questions">							
			
					<label style="color: #FFF; font-family: calibri;" for="q1">Which team is the #1 favorite for the championship?</label> <br />
					<select required="required" name="q1" id="q1" class="span3">
						<option value="">Select an option</option>
						<option value="BB">Ball Breakers</option>
						<option value="Bears">Bears</option>
						<option value="Gs">Gorillas</option>
						<option value="iSS">Inter Soccer Stars</option>
						<option value="nG">NextGen</option>
						<option value="s7">Super 7</option>									
					</select>
					
					<label style="color: #FFF; font-family: calibri;" for="q2">Which team are the biggest underdog in the league?</label> <br />
					<select required="required" name="q2" id="q2" class="span3">
						<option value="">Select an option</option>
						<option value="BB">Ball Breakers</option>
						<option value="Bears">Bears</option>
						<option value="Gs">Gorillas</option>
						<option value="iSS">Inter Soccer Stars</option>
						<option value="nG">NextGen</option>
						<option value="s7">Super 7</option>									
					</select>
					
					<label style="color: #FFF; font-family: calibri;" for="q3">Who will be top scorer?</label> <br />
					<select required="required" name="q3" id="q3" class="span3">
						<option value="">Select an option</option>
						<option value="Ailton">Ailton</option>
						<option value="Ashley">Ashley</option>
						<option value="Burni">Burni</option>
						<option value="CARLEETOS">CARLEETOS</option>
						<option value="Chalkeh">Chalkeh</option>
						<option value="ChouPo">ChouPo</option>
						<option value="Cuppatea">Cuppatea</option>
						<option value="Daap">Daap</option>
						<option value="DBD">DBD</option>
						<option value="Deluxe">Deluxe</option>
						<option value="Denneh">Denneh</option>
						<option value="Destran">Destran</option>
						<option value="Diakun">Diakun</option>
						<option value="Drogba">Drogba</option>
						<option value="Earneh">Earneh</option>
						<option value="EltonJohn">EltonJohn</option>
						<option value="Filip">Filip</option>
						<option value="Flame">Flame</option>
						<option value="Fluke">Fluke</option>
						<option value="Fonzik">Fonzik</option>
						<option value="Fuzz">Fuzz</option>
						<option value="GaMs">GaMs</option>
						<option value="Ginixx">Ginixx</option>
						<option value="Goldeh">Goldeh</option>
						<option value="Grandie">Grandie</option>
						<option value="Greggles">Greggles</option>
						<option value="Gunner">Gunner</option>
						<option value="h0w">h0w</option>
						<option value="Hexo">Hexo</option>
						<option value="Hiei">Hiei</option>
						<option value="Hpayer">Hpayer</option>
						<option value="Iran">Iran</option>
						<option value="JB3">JB3</option>
						<option value="Kaim">Kaim</option>
						<option value="Kajia">Kajia</option>
						<option value="Kaka22">Kaka22</option>
						<option value="Katsuo">Katsuo</option>
						<option value="Khaledinho">Khaledinho</option>
						<option value="Kirby">Kirby</option>
						<option value="Km">Km</option>
						<option value="Kobe">Kobe</option>
						<option value="LagHack">LagHack</option>
						<option value="Larsson">Larsson</option>
						<option value="Lua">Lua</option>
						<option value="Luisa">Luisa</option>
						<option value="Maaby">Maaby</option>
						<option value="Marsi">Marsi</option>
						<option value="MeanMachine">MeanMachine</option>
						<option value="Modiga">Modiga</option>
						<option value="Monkeyclone">Monkeyclone</option>
						<option value="Moses">Moses</option>
						<option value="Neuromancer">Neuromancer</option>
						<option value="Niang">Niang</option>
						<option value="Night-Fire">Night-Fire</option>
						<option value="Nuri">Nuri</option>
						<option value="Orius">Orius</option>
						<option value="Pauer">Pauer</option>
						<option value="Quincy">Quincy</option>
						<option value="Rage">Rage</option>
						<option value="Rahmstein">Rahmstein</option>
						<option value="Realms">Realms</option>
						<option value="Rhino">Rhino</option>
						<option value="Robi">Robi</option>
						<option value="Romdi">Romdi</option>
						<option value="Roq">Roq</option>
						<option value="RvdV">RvdV</option>
						<option value="Ryaninho">Ryaninho</option>
						<option value="Saddeh">Saddeh</option>
						<option value="Salix">Salix</option>
						<option value="Seaneh">Seaneh</option>
						<option value="Seven|Up">Seven|Up</option>
						<option value="Shagwa">Shagwa</option>
						<option value="Simao">Simao</option>
						<option value="Simu">Simu</option>
						<option value="Skum">Skum</option>
						<option value="Sudders">Sudders</option>
						<option value="Termi">Termi</option>
						<option value="Tet">Tet</option>
						<option value="Thing'e'">Thing'e'</option>
						<option value="TopCat">TopCat</option>
						<option value="Tsubasa">Tsubasa</option>
						<option value="Walsh">Walsh</option>
						<option value="Wilmots">Wilmots</option>
						<option value="XaviT">XaviT</option>
						<option value="Xedem">Xedem</option>
						<option value="Yvus">Yvus</option>
						<option value="Zapdos">Zapdos</option>
						<option value="Zlatan">Zlatan</option>
					</select>
					
				<label style="color: #FFF; font-family: calibri;" for="q4">Who will be assist leader?</label> <br />
					<select required="required" name="q4" id="q4" class="span3">
						<option value="">Select an option</option>
						<option value="Ailton">Ailton</option>
						<option value="Ashley">Ashley</option>
						<option value="Burni">Burni</option>
						<option value="CARLEETOS">CARLEETOS</option>
						<option value="Chalkeh">Chalkeh</option>
						<option value="ChouPo">ChouPo</option>
						<option value="Cuppatea">Cuppatea</option>
						<option value="Daap">Daap</option>
						<option value="DBD">DBD</option>
						<option value="Deluxe">Deluxe</option>
						<option value="Denneh">Denneh</option>
						<option value="Destran">Destran</option>
						<option value="Diakun">Diakun</option>
						<option value="Drogba">Drogba</option>
						<option value="Earneh">Earneh</option>
						<option value="EltonJohn">EltonJohn</option>
						<option value="Filip">Filip</option>
						<option value="Flame">Flame</option>
						<option value="Fluke">Fluke</option>
						<option value="Fonzik">Fonzik</option>
						<option value="Fuzz">Fuzz</option>
						<option value="GaMs">GaMs</option>
						<option value="Ginixx">Ginixx</option>
						<option value="Goldeh">Goldeh</option>
						<option value="Grandie">Grandie</option>
						<option value="Greggles">Greggles</option>
						<option value="Gunner">Gunner</option>
						<option value="h0w">h0w</option>
						<option value="Hexo">Hexo</option>
						<option value="Hiei">Hiei</option>
						<option value="Hpayer">Hpayer</option>
						<option value="Iran">Iran</option>
						<option value="JB3">JB3</option>
						<option value="Kaim">Kaim</option>
						<option value="Kajia">Kajia</option>
						<option value="Kaka22">Kaka22</option>
						<option value="Katsuo">Katsuo</option>
						<option value="Khaledinho">Khaledinho</option>
						<option value="Kirby">Kirby</option>
						<option value="Km">Km</option>
						<option value="Kobe">Kobe</option>
						<option value="LagHack">LagHack</option>
						<option value="Larsson">Larsson</option>
						<option value="Lua">Lua</option>
						<option value="Luisa">Luisa</option>
						<option value="Maaby">Maaby</option>
						<option value="Marsi">Marsi</option>
						<option value="MeanMachine">MeanMachine</option>
						<option value="Modiga">Modiga</option>
						<option value="Monkeyclone">Monkeyclone</option>
						<option value="Moses">Moses</option>
						<option value="Neuromancer">Neuromancer</option>
						<option value="Niang">Niang</option>
						<option value="Night-Fire">Night-Fire</option>
						<option value="Nuri">Nuri</option>
						<option value="Orius">Orius</option>
						<option value="Pauer">Pauer</option>
						<option value="Quincy">Quincy</option>
						<option value="Rage">Rage</option>
						<option value="Rahmstein">Rahmstein</option>
						<option value="Realms">Realms</option>
						<option value="Rhino">Rhino</option>
						<option value="Robi">Robi</option>
						<option value="Romdi">Romdi</option>
						<option value="Roq">Roq</option>
						<option value="RvdV">RvdV</option>
						<option value="Ryaninho">Ryaninho</option>
						<option value="Saddeh">Saddeh</option>
						<option value="Salix">Salix</option>
						<option value="Seaneh">Seaneh</option>
						<option value="Seven|Up">Seven|Up</option>
						<option value="Shagwa">Shagwa</option>
						<option value="Simao">Simao</option>
						<option value="Simu">Simu</option>
						<option value="Skum">Skum</option>
						<option value="Sudders">Sudders</option>
						<option value="Termi">Termi</option>
						<option value="Tet">Tet</option>
						<option value="Thing'e'">Thing'e'</option>
						<option value="TopCat">TopCat</option>
						<option value="Tsubasa">Tsubasa</option>
						<option value="Walsh">Walsh</option>
						<option value="Wilmots">Wilmots</option>
						<option value="XaviT">XaviT</option>
						<option value="Xedem">Xedem</option>
						<option value="Yvus">Yvus</option>
						<option value="Zapdos">Zapdos</option>
						<option value="Zlatan">Zlatan</option>
					</select>
							
			</div>
			
			<div class="confirm">

				<input type="submit" class="btn btn-success" name="submit" value="Submit" />
			
			</div>

		</fieldset>

	</form>