	<div class="rules">
	
		<div class="rules-index">
		
				<h2>1. Preface</h2>
				
				<p>1.1 All players participating in the league have to accept the following rules. These rules are adjusted uncomformably and thus have to be checked regularly by the player.	
				Only big changes will be announced.</p>
				
				<h2>2. Code of conduct</h2>
				
				<p>2.1 Disrespecting other team and/or players is not allowed. After multiple offences like this, the staff can decide to ban a player for a period of time.</p>
				
				<p>2.2 Racism is not allowed, all cases will be reviewed. When the staff decides the rule has been broken it will mean a ban from the IOS League for a period of time.</p>
				
				<p>2.3 Using cheats or any other exploit on purpose will result in a permanent ban.</p>
				
				<p>2.4 Leaving the game before FT can result in a ban for a period of time.</p>
				
				<p>2.5 If multiple players of the same team violate rule 2.4, that team will get a big punishment.</p>
				
				
				<h2>3. League rules</h2>
				
				<p>3.1 Each team will play each other twice.</p>
				
				<p>3.2 League games will not have ET.</p>
				
				<p>3.3 Rules for classification: 1) points; 2) goal difference; 3) number of goals scored.</p>
				
				<p>3.4 If all 3 of the rules are the same between 2 or more teams. There will be a 'deciding' match played including extra time and penalties shoot-out.</p>
				
				<h2>4. Cup rules</h2>
				
				<p>4.1 Cup will start after Matchweek 6.</p>
				
				<p>4.2 Cup games will have ET and eventually penalty shoot-out if needed.</p>
				
				<p>4.3 The #1 and #2 seed after Matchweek 5 will get a bye for the quarter-final.</p>
				
				<p>4.4 The #3 will face #6, #4 will face #5 in quarter-final.</p>
				
				<p>4.5 Winner of #3 vs #6 will face the #1. Winner of #4 vs #5 will face the #2.</p>
			
				
				<h2>5. Match rules</h2>
				
				<p style="font-weight: 900;">5.1 Date and Time</p>
				
				<p>5.1.1 The official league timezone is Europe/Amsterdam.</p>
				
				<p>5.1.2 League matches will be played on fixed days. The league match days is Sunday, Cup games will be played Wednesdays and matches will be played between 17:00 and 22:00.</p>
				
				<p>5.1.3 All matches will be played on the <a href="http://www.simrai.com">SimRai</a> servers which are located in the Netherlands.</p>
				
				<p style="font-weight: 900;">5.2 Match details</p>
			
				<p>5.2.1 All matches will be played in a 7 versus 7 format.</p>
				
				<p>5.2.2 All matches will be 20 minutes in length.</p>
				
				<p>5.2.3 Matches will be played on the map "ioss_7v7iran_v12 or ioss_7testadium_v3".</p>
				
				<p>5.2.4 The captain of the home team can decide the map that will be played on.</p>
				
				<p>5.2.5 When the match has finished, do not leave the server immediately. Wait at least 3 seconds.</p>
				
				<p style="font-weight: 900;">5.3 Lagged player, Substitution and Timeouts</p>
				
				<p>5.3.1 Substitutions are allowed during matches, however once a player has been substituted they cannot be brought back on. The maximum substitutions per match is 3 per team.</p>
				
				<p>5.3.2 You can use 2 timeouts of 1 minute whenever needed. Do not use this if a player lagged out or a substitution, the admin will call a timeout for that.</p>
				
				<p>5.3.3 If a player has lagged out is the duty of the captain to ask the current server admin for a timeout, once this has been done the ball must be put out of the play and then respective captain will have 5 minutes to either get their player back or sub a player in. If they cannot get a substitution or their lagged player back within the 5 minutes, the game will continue with 6 players. However the lagged player in question can still rejoin the server if they manage to get back on the server. </p>
			
				<p>5.3.4 The maximum timeouts you can call is 5. 2 for tactics and 3 for substitution for player lagged out. </p>
				
				<p>5.3.5 Maximum 5 players per team can join the league server to spectate. Eventually they can substitute whenever someone lagged out (remember substituted player cannot be brought back in!)</p>

				
				
				<h2>6. Other rules</h2>
				
				<p>6.1 A team needs at least 12 players with a maximum of 18 players.Teams be able to have more members but 18 is the maximum for registration.</p>
				
				<p>6.2 If you receive a 2nd yellow card, or a direct red card. You must wait the entire length of the ban before you can rejoin the game. The team cannot make substitutions for a currently sent off player.</p>
				
				<p>6.3 Players will get an automatic 1 game ban for the next game after 5 yellow. That includes Cup games. For direct red it will be reviewed if he will get a 1 game ban or not.</p>
				
				<p>6.4 All players must be on the server before the scheduled time. Else rule 4.3 might start working</p>
			
				<p>6.5 If a team doesn't turn up for a scheduled match without notifying the staff, the other team will recieve a default 3-0 victory.</p>
				
				<p>6.6 Mercs/Loans are not allowed to play league matches.</p>
				
				<p>6.7 Each player needs a valid SteamID to take part in the League. A player is only allowed to use one Steam ID.</p>
				
				<p>6.8 You have to use the name that you are known of. (which are on the website)</p>
				
				<p>6.9 Any bug goals will be removed from the score.</p>
				
				
				<h2>7. Transfers</h2>
				
				<p>7.1 A player can only play for 2 teams if he moves in the transferweek which will be between Matchweek 5 and 6.</p>
				
				<p>7.2 A player cannot play for 2 different teams within the timeframe of the league. For instance is Player X decides to leave their team after having already played a match for the league, they are not allowed to play until the next transferweek or the rest of the league.</p>
			
				<p>7.3 Clans can sign a free agent at any period during a season but must be registered 24 hours before the next match to be eligible.</p>				
				
				<p>7.4 Teams signing free agents outside the transfer window are only allowed up to 3 free agents during a season.</p>

				<p>7.5 The free agent ruling only applies to those players that have not been registered to a clan during the current season.</p>
				
				<p>7.6 If you release a player, you can not 'fill' that spot with another player until the next transfer week or the rest of the league. That includes free agents.</p>
				
				<p>7.7 Transferweek starts Monday 15 July and ends Saturday 20 July.</p>
				
				<h2>8. Folding</h2>

				<p>8.1 If a team folds or leave the league during the season. Their results will be removed against all teams.</p>
				
			</div>
	
	</div>