	<div class="rules">
	
		<div class="rules-index">
		
				<h2>Organiser:</h2>
				<p>Iran</p>
				
				<h2>Servers:</h2>
				<p>Orius</p>
				
				<h2>Match Admins:</h2>
				<p>Gunner <br />
				Gold <br />
				Kobe <br />
				DBD <br />
				Roq </p>
				
				<h2>Streaming:</h2>
				<p>Rhino <br />
				Kirby <br /> 
				Flame</p>
				
				<h2>Writers:</h2>
				<p>Gold <br />
				DBD <br />
				Tet</p>
				
				<h2>Interviews: </h2>
				<p>DBD <br />
				Tet <br />
				
				<h2>Judging panel: </h2>
				<p>Gunner <br />
				Roq <br />
				JB3 <br />
				Flame <br />
				
				<h2>Website: </h2>
				<p>Strexx

			</div>
	
	</div>