<table class="tablesorter" cellspacing="1">             
	<thead>
		<tr> 
			<th class="headSort header headerSortDown">Pos&nbsp;</th>
			<th class="headSort header">Team</th>
			<th class="headSort header">Pld</th>
			<th class="headSort header">W</th>
			<th class="headSort header">D</th>
			<th class="headSort header">L</th>
			<th class="headSort header">GF</th>
			<th class="headSort header">GA</th> 
			<th class="headSort header">GD</th> 
			<th class="header">Pts</th>
		</tr> 
	</thead> 
	<tbody class="standingrank"> 
	
			<?php 
			foreach( $this->standings as $standing ):
        
			echo'<tr> 
					<td>' . $standing['position'] . '</td> 
					<td>' . $standing['club'] . '</td> 
					<td>' . $standing['games'] . '</td> 
					<td>' . $standing['won'] . '</td> 
					<td>' . $standing['draw'] . '</td> 
					<td>' . $standing['loss'] . '</td>
					<td>' . $standing['goalsfor'] . '</td>				
					<td>' . $standing['goalsagainst'] . '</td>
					<td>' . $standing['goaldifference'] . '</td>
					<td>' . $standing['points'] . '</td>
			</tr>';
			endforeach;
			?> 
		
	</tbody>

	
</table>

<script type="text/javascript">

$(function() {
    $("table").tablesorter({ 
        // sort on the first column and third column, order asc 
        sortList: [[0,0],[0,0]] 
    }); 
});

</script>

<script type="text/javascript" src="assets/js/jquery.tablesorter.js"></script>