	<table class="tablesorter" cellspacing="1">             
		<thead>
			<tr> 
				<th class="headSort">Period</th>
				<th class="headSort">Player</th>
				<th class="headSort">Position</th>
				<th class="headSort">Old Team</th>
				<th class="headSort">New Team</th>
				<th class="headSort">Punishment</th>
			</tr> 
		</thead> 
		<tbody class="transfers"> 	
		
			<?php 
			foreach($this->transfers as $transfer):
        
			echo'<tr> 
					<td>' . $transfer['period'] . '</td> 
					<td>' . $transfer['name'] . '</td> 
					<td>' . $transfer['position'] . '</td> 
					<td>' . $transfer['oldteam'] . '</td> 
					<td>' . $transfer['newteam'] . '</td> 
					<td>' . $transfer['punishment'] . '</td>
			</tr>';
			endforeach;
			?> 
			
		</tbody> 
	</table>
	
	<script type="text/javascript">

	$(function() {
		$("table").tablesorter({ 
			// sort on the first column and third column, order asc 
			sortList: [[0,0],[0,0]] 
		}); 
	});

	</script>

	<script type="text/javascript" src="assets/js/jquery.tablesorter.js"></script> 