<h2>Welcome</h2>
<p id="page-intro">&nbsp;</p>

<ul class="shortcut-buttons-set">

    <li><a class="shortcut-button" href="dashboard/backup"><span>
        <?php echo $this->translate('Backup database'); ?>
    </span></a></li>
    
    <li><a class="shortcut-button" href="dashboard/cache"><span>
        <?php echo $this->translate('Delete all cache'); ?>
    </span></a></li>
        
</ul>

<div class="clear"></div>