<?php
$this->layout()->title = $this->translate('Standings overview');
?>
<section class=categories>
    <table>
        <thead>
            <tr>
                <th><?php echo $this->translate('Position');?>
				<th><?php echo $this->translate('Team');?>
				<th><?php echo $this->translate('Played');?>
				<th><?php echo $this->translate('Won');?>
				<th><?php echo $this->translate('Drawn');?>
				<th><?php echo $this->translate('Lost');?>
				<th><?php echo $this->translate('Goals For');?>
				<th><?php echo $this->translate('Goals Against');?>
				<th><?php echo $this->translate('Goal Difference');?>
				<th><?php echo $this->translate('Points');?>
                <th width="90">Active
                <th width="50">&nbsp;
                <th width="50">&nbsp;
        </thead>
        <tbody>
            <?php 
            $items = $this->items;
            foreach($items as $i => $item):?>
            <tr>
                <td><?php echo $item['position']; ?></td>
				<td><?php echo $item['club']; ?></td>
				<td><?php echo $item['games']; ?></td>
				<td><?php echo $item['won']; ?></td>
				<td><?php echo $item['draw']; ?></td>
				<td><?php echo $item['loss']; ?></td>
				<td><?php echo $item['goalsfor']; ?></td>
				<td><?php echo $item['goalsagainst']; ?></td>
				<td><?php echo $item['goaldifference']; ?></td>
				<td><?php echo $item['points']; ?></td>
                <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id'])) ?>"><?php echo $this->translate('Update');?></a></td>
                <td class=delete><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id'])) ?>"><?php echo $this->translate('Delete');?></a></td>
            </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</section>