<?php $this->layout()->title = 'Inloggen';?>
<div id="login-content">
    <form method=POST>
        
        <p>
            <label>E-mail</label>
            <input class="text-input" name=email />
        </p>
        <div class="clear"></div>
        <p>
            <label>Password</label>
            <input class="text-input" type="password" name=password />
        </p>
        <div class="clear"></div>
        <div class="clear"></div>
        <p>
            <input class="button" type="submit" value="Sign In" />
        </p>
        
    </form>
</div>