<?php
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$form   = $this->form;
$forms  = $form->getSubForms();

$submit = '<input type=submit class=button value="' . $this->translate('Save')  . '" />';
?>
       
<form class="standard" method=POST>
    
<div class="content-box">
    <div class="content-box-header">
        <ul class="content-box-tabs"> 
            <li><a href="#tab-general" class="default-tab"><?php echo $this->translate('General information');?></a></li>
            <?php
            foreach($forms as $i => $subform):
            ?> 
            <li><a href="#tab<?php echo $i;?>"><?php echo $subform->getName();?></a></li>
            <?php
            endforeach;
            ?>
        </ul> 
        <div class="clear"></div>
    </div>
    <div class="content-box-content">
        
        <!-- General info -->
        <div class="tab-content default-tab" id="tab-general">
            <p>
                <label class=required><?php echo $this->translate('Parent business');?></label>
                <?php echo $form->getElement('business_id') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Image');?></label>
                <?php echo $form->getElement('image')->addClass('image1'); ?>
                <a href="javascript:void();" rel="1" class="image_browser">Upload image</a>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Show in menu');?></label>
                <?php echo $form->getElement('show_menu') ?>
            </p>
            <p>
                <?php echo $submit;?>
            </p>  
            <div class="clear"></div>
            
        </div>
        
        <!-- Language info -->
        <?php
        foreach($forms as $i => $subform):
        ?>        
        <div class="tab-content" id="tab<?php echo $i;?>">           
            <p>
                <label class=required><?php echo $this->translate('Name');?></label>
                <?php echo $subform->getElement('name') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Title');?></label>
                <?php echo $subform->getElement('title') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Description');?></label>
                <?php echo $subform->getElement('description') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Keywords');?></label>
                <?php echo $subform->getElement('keywords') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Content');?></label>
                <?php echo $subform->getElement('content')->addClass('ck') ?>
            </p>
            <p>
                <?php echo $submit;?>
            </p>   
        </div>
        <?php
        endforeach;
        ?>
        
    </div>
</div>

</form>  

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){

    // display hidden images
    $('.image_preview').each(function(){
        if($(this).attr('src') != '../')
            $(this).show();
    });

    var active = '';    
    function SetFileField(fileUrl) {
        $('.image' + active).val(fileUrl);
        $('.preview' + active).attr('src','../' + fileUrl).show();
    }
    
    var finder = new CKFinder();
    finder.selectActionFunction = SetFileField;
    $(".image_browser").bind("click", function(){ 
        active = $(this).attr('rel');
        finder.popup();
    });       
}); 
<?php $this->headScript()->captureEnd(); ?>