<?php
$action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$form   = $this->form;
$forms  = $form->getSubForms();

$submit = '<input type=submit class=button value="' . $this->translate('Save')  . '" />';
?>
       
<form class="standard" method=POST>
    
<div class="content-box">
    <div class="content-box-header">
        <ul class="content-box-tabs">
            <li><a href="#tabgeneral" class="current">General</a></li>
            <?php
            $j = 0;
            foreach($forms as $i => $subform):
            ?>
            <?php
            if($j == 0)
            {
                echo '<li><a href="#tab'. $subform->getName() .'">'. $subform->getName() .'</a></li>';
            }
            else
            {
                echo '<li><a href="#tab'. $subform->getName() .'">'. $subform->getName() .'</a></li>';
            }
            ?>
            <?php
            $j++;
            endforeach;
            ?>
        </ul> 
        <div class="clear"></div>
    </div>
    <div class="content-box-content">
            
        <div>      
            <p>
                <label class=required><?php echo $this->translate('Stage');?></label>
                <?php echo $form->getElement('stage') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Date');?></label>
                <?php echo $form->getElement('date')->addClass('date-input') ?>
            </p>
			<p>
                <label class=required><?php echo $this->translate('Home');?></label>
                <?php echo $form->getElement('hometeam') ?>
            </p>
            <p>
                <label class=required><?php echo $this->translate('Score');?></label>
                <?php echo $form->getElement('score') ?>
            </p>
			<p>
                <label class=required><?php echo $this->translate('Away');?></label>
                <?php echo $form->getElement('awayteam') ?>
            </p>
			<p>
                <label class=required><?php echo $this->translate('Time (CEST)');?></label>
                <?php echo $form->getElement('time') ?>
            </p>
			<p>
                <label class=required><?php echo $this->translate('Admin');?></label>
                <?php echo $form->getElement('admin') ?>
            </p>		
            <p>
                <?php echo $submit; ?>
            </p>   
        </div>
        
    </div>
</div>

</form>  

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){

    // display hidden images
    $('.image_preview').each(function(){
        if($(this).attr('src') != '../')
            $(this).show();
    });

    var active = '';    
    function SetFileField(fileUrl) {
        $('.image' + active).val(fileUrl);
        $('.preview' + active).attr('src','../' + fileUrl).show();
    }
    
    var finder = new CKFinder();
    finder.selectActionFunction = SetFileField;
    $(".image_browser").bind("click", function(){ 
        active = $(this).attr('rel');
        finder.popup();
    });
}); 
<?php $this->headScript()->captureEnd(); ?>