			<div id="fixtures">
			
				<div id="events">
			
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3">Match Events</td></tr>
							<tr>
								<th>Minute</th>
								<th>Event</th>
								<th>Player</th>
							</tr>
						</thead>
						
						<tbody>
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>	
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>								
						</tbody>
					</table>
				</div>
				
				<div id="lineup">
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3">Starting VII</td></tr>
							<tr>
								<th>Home</th>
								<th>Away</th>
							</tr>
						</thead>	
						<tbody>
							<tr>
								<td>GK: </td>
								<td>GK: </td>
							</tr>
							<tr>
								<td>LB: </td>
								<td>LB: </td>
							</tr>
							<tr>
								<td>RB: </td>
								<td>RB: </td>
							</tr>
							<tr>
								<td>CDM: </td>
								<td>CDM: </td>
							</tr>
							<tr>
								<td>CAM: </td>
								<td>CAM: </td>
							</tr>
							<tr>
								<td>LW: </td>
								<td>LW: </td>
							</tr>	
							<tr>
								<td>RW: </td>
								<td>RW: </td>
							</tr>							
						</tbody>	
					</table>
						<a href="" target="_blank"><button class="btn">Screenshot</button></a>
						<a href=""><button class="btn">Back to Fixtures</button></a>			
				</div>
			
		  
				<div id="games">
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3"> - </td></tr>
							<tr>
								<th>Home</th>
								<th>Stats</th>
								<th>Away</th>
							</tr>
						</thead>					
						<tbody>
							<tr>
								<td></td>
								<td>Goals</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Total Shots</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Shots On Target</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Possession</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Interceptions</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Corners</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Total Passes</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Passes Completed</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Fouls</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Yellow Cards</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Red Cards</td>
								<td></td>
							</tr>
							<tr>
								<td></td>
								<td>Distance Covered</td>
								<td></td>
							</tr>								
						</tbody>		
					</table>			
				</div>
			</div>