			<div id="fixtures">
			
				<div id="events">
			
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="4">Match Events</td></tr>
							<tr>
								<th>Period</th>
								<th>Minute</th>
								<th>Event</th>
								<th>Player</th>
							</tr>
						</thead>
						
						<tbody>
						
						<?php 
							$db = Zend_Registry::get('db');
							foreach( $this->events as $event ): 
							$player = $db->fetchRow('SELECT * FROM players WHERE steam_id = ?', $event['steam_id']);

							switch ($event['event']) {
							    case "YELLOW CARD":
							        $class = 'icons-yellow-card';
							        break;
							    case "RED CARD":
							        $class = 'icons-red-card';
							        break;
							    case "SECOND YELLOW":
							        $class = 'icons-red-card';
							        break;
							    case "GOAL":
							        $class = 'icons-goal';
							        break;
							    case "SAVE":
							        $class = 'icons-save';
							        break;
							    case "MISS":
							        $class = 'icons-miss';
							        break;
							}
						?>
							<tr>
								<td><?php echo $event['period']; ?></td>
								<td><?php echo $event['minute']; ?></td>
								<td class="<?php echo $class; ?>">&nbsp;</td>
								<td><?php echo $player['name']; ?></td>
							</tr>

						<?php endforeach; ?>

						</tbody>
					</table>
				</div>
				
				<div id="positions">
				
					<div class="top">
						<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="4">Starting VII</td></tr>
							<tr>
								<th>Home</th>
								<th>Away</th>
							</tr>
						</thead>
						</table>
					</div>
					
					<div class="left-home">
						<br />
						<ul>
							<?php 
								foreach($this->hPositions as $hPosition): 
									$player = $db->fetchRow('SELECT * FROM players WHERE steam_id = ?', $hPosition['steam_id']);

							?>
					
								
									<li><?php echo $hPosition['position']; ?>: <?php echo $player['name']; ?></li>
								
					

							<?php endforeach; ?>
					</div>
					
					<div class="right-away">
						<br />
							<?php 
								foreach($this->aPositions as $aPosition): 
									$player = $db->fetchRow('SELECT * FROM players WHERE steam_id = ?', $aPosition['steam_id']);
							?>
								
									<li><?php echo $aPosition['position']; ?>: <?php echo $player['name']; ?></li>


								
							<?php endforeach; ?>
							
							</ul>
							
							<br />
					</div>
					
					<div class="buttons">
						<a href=""><button class="btn">Index</button></a>	
						<a href="schedules"><button class="btn">Schedules</button></a>	
					</div>

				</div>	

						  
				<div id="games">
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3"><?php echo $this->matchInfo['h_team'] . '&nbsp;' . $this->matchInfo['h_goals']  ?>-<?php echo  $this->matchInfo['a_goals'] . '&nbsp;' . $this->matchInfo['a_team']?></td></tr>
							<tr>
								<th>Home</th>
								<th>Stats</th>
								<th>Away</th>
							</tr>
						</thead>					
						<tbody>

							<tr>
								<td><?php echo $this->matchInfo['h_goals'] ?></td>
								<td>Goals</td>
								<td><?php echo $this->matchInfo['a_goals'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_shots'] ?></td>
								<td>Total Shots</td>
								<td><?php echo $this->matchInfo['a_shots'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_shotsot'] ?></td>
								<td>Shots On Target</td>
								<td><?php echo $this->matchInfo['a_shotsot'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_possession'] ?>%</td>
								<td>Possession</td>
								<td><?php echo $this->matchInfo['a_possession'] ?>%</td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_interceptions'] ?></td>
								<td>Interceptions</td>
								<td><?php echo $this->matchInfo['a_interceptions'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_corners'] ?></td>
								<td>Corners</td>
								<td><?php echo $this->matchInfo['a_corners'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_passes'] ?></td>
								<td>Total Passes</td>
								<td><?php echo $this->matchInfo['a_passes'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_passescp'] ?></td>
								<td>Passes Completed</td>
								<td><?php echo $this->matchInfo['a_passescp'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_fouls'] ?></td>
								<td>Fouls</td>
								<td><?php echo $this->matchInfo['a_fouls'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_ycards'] ?></td>
								<td>Yellow Cards</td>
								<td><?php echo $this->matchInfo['a_ycards'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_rcards'] ?></td>
								<td>Red Cards</td>
								<td><?php echo $this->matchInfo['a_rcards'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_distance'] ?></td>
								<td>Distance Covered</td>
								<td><?php echo $this->matchInfo['a_distance'] ?></td>
							</tr>								
						</tbody>		
					</table>			
				</div>
				
			</div>