			<div id="fixtures">
			
				<div id="events">
			
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="4">Match Events</td></tr>
							<tr>
								<th>Period</th>
								<th>Minute</th>
								<th>Event</th>
								<th>Player</th>
							</tr>
						</thead>
						
						<tbody>
						
						<?php 
							$db = Zend_Registry::get('db');
							foreach( $this->events as $event ): 
							$player = $db->fetchRow('SELECT * FROM players WHERE steam_id = ?', $event['steam_id']);
						?>
							<tr>
								<td><?php echo $event['period']; ?></td>
								<td><?php echo $event['minute']; ?></td>
								<td><?php echo $event['event']; ?></td>
								<td><?php echo $player['name']; ?></td>
							</tr>

						<?php endforeach; ?>

						</tbody>
					</table>
				</div>
				
				<div id="lineup">
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3">Starting VII</td></tr>
							<tr>
								<th>Home</th>
								<th>Away</th>
							</tr>
						</thead>	
						<tbody>
							<tr>
								<td>GK: </td>
								<td>GK: </td>
							</tr>
							<tr>
								<td>LB: </td>
								<td>LB: </td>
							</tr>
							<tr>
								<td>RB: </td>
								<td>RB: </td>
							</tr>
							<tr>
								<td>CDM: </td>
								<td>CDM: </td>
							</tr>
							<tr>
								<td>CAM: </td>
								<td>CAM: </td>
							</tr>
							<tr>
								<td>LW: </td>
								<td>LW: </td>
							</tr>	
							<tr>
								<td>RW: </td>
								<td>RW: </td>
							</tr>							
						</tbody>	
					</table>
						<a href="schedules"><button class="btn">Back to Fixtures</button></a>			
				</div>
			
		  
				<div id="games">
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3"><?php echo $this->matchInfo['h_team'] . '&nbsp;' . $this->matchInfo['h_goals']  ?>-<?php echo  $this->matchInfo['a_goals'] . '&nbsp;' . $this->matchInfo['a_team']?></td></tr>
							<tr>
								<th>Home</th>
								<th>Stats</th>
								<th>Away</th>
							</tr>
						</thead>					
						<tbody>

							<tr>
								<td><?php echo $this->matchInfo['h_goals'] ?></td>
								<td>Goals</td>
								<td><?php echo $this->matchInfo['a_goals'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_shots'] ?></td>
								<td>Total Shots</td>
								<td><?php echo $this->matchInfo['a_shots'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_shotsot'] ?></td>
								<td>Shots On Target</td>
								<td><?php echo $this->matchInfo['a_shotsot'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_possession'] ?></td>
								<td>Possession</td>
								<td><?php echo $this->matchInfo['a_possession'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_interceptions'] ?></td>
								<td>Interceptions</td>
								<td><?php echo $this->matchInfo['a_interceptions'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_corners'] ?></td>
								<td>Corners</td>
								<td><?php echo $this->matchInfo['a_corners'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_passes'] ?></td>
								<td>Total Passes</td>
								<td><?php echo $this->matchInfo['a_passes'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_passescp'] ?></td>
								<td>Passes Completed</td>
								<td><?php echo $this->matchInfo['a_passescp'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_fouls'] ?></td>
								<td>Fouls</td>
								<td><?php echo $this->matchInfo['a_fouls'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_ycards'] ?></td>
								<td>Yellow Cards</td>
								<td><?php echo $this->matchInfo['a_ycards'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_rcards'] ?></td>
								<td>Red Cards</td>
								<td><?php echo $this->matchInfo['a_rcards'] ?></td>
							</tr>
							<tr>
								<td><?php echo $this->matchInfo['h_distance'] ?></td>
								<td>Distance Covered</td>
								<td><?php echo $this->matchInfo['a_distance'] ?></td>
							</tr>								
						</tbody>		
					</table>			
				</div>
			</div>