			<div id="fixtures">
			
				<div id="profile">
			
					<table class="table gametable">
						<thead>
							<tr class="gamename" ><td colspan="3">Match Events</td></tr>
							<tr>
								<th>Minute</th>
								<th>Event</th>
								<th>Player</th>
							</tr>
						</thead>
						
						<tbody>
							<tr>
								<td>-</td>
								<td>-</td>
								<td>-</td>
							</tr>									
						</tbody>
					</table>
					
				</div>
				

			</div>