<?php
$this->layout()->title = $this->translate('Punishments overview');
?>
<section class=categories>
    <table>
        <thead>
            <tr>
                <th><?php echo $this->translate('Date');?>
				<th><?php echo $this->translate('Player');?>
				<th><?php echo $this->translate('Team');?>
				<th><?php echo $this->translate('Penalty');?>
				<th><?php echo $this->translate('Reason');?>
                <th width="90">Active
                <th width="50">&nbsp;
                <th width="50">&nbsp;
        </thead>
        <tbody>
            <?php 
            $items = $this->items;
            foreach($items as $i => $item):?>
            <tr>
                <td><?php echo $item['date']; ?></td>
				<td><?php echo $item['name']; ?></td>
				<td><?php echo $item['team']; ?></td>
				<td><?php echo $item['punishment']; ?></td>
				<td><?php echo $item['reason']; ?></td>
                <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item['id'])) ?>"><?php echo $this->translate('Update');?></a></td>
                <td class=delete><a href="<?php echo $this->url(array('action' => 'delete', 'id' => $item['id'])) ?>"><?php echo $this->translate('Delete');?></a></td>
            </tr>
            <?php
            endforeach;
            ?>
        </tbody>
    </table>
</section>